name: Post deployment test e2e
run-name: Trigger by deployment of get-deals repository
on:
  repository_dispatch:
    types: [vercel-deploy-success]

env:
  BASE_URL: https://get-deals.vercel.app
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Summary Test run information
        run: |
          SHA=${{github.event.client_payload.sha}}
          SHORT_SHA=${SHA::8}
          echo "### Triggered by get-deals deploy" >> "$GITHUB_STEP_SUMMARY"
          echo "Commit: [${SHORT_SHA}](${{ github.event.client_payload.commit_url }})" >> "$GITHUB_STEP_SUMMARY"
          echo "Environment URL: [${{ github.event.client_payload.environment_url }}](${{ github.event.client_payload.environment_url }})" >> "$GITHUB_STEP_SUMMARY"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test
        run: |
          yarn install
          yarn playwright:install
          yarn test --grep "@ID_1"
