name: Post deployment test e2e
run-name: Trigger by deployment of get-deals repository
on:
  repository_dispatch:
    types: [vercel-deploy-success]

env:
  BASE_URL: ${{github.event.client_payload.url}}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Summary Test run information
        run: |
          echo "### Triggered by get-deals deploy" >> "$GITHUB_STEP_SUMMARY"
          echo "Commit: [${{ github.event.client_payload.sha }}](${{ github.event.client_payload.commit_url }})" >> "$GITHUB_STEP_SUMMARY"
          echo "Deployed URL: ${{github.event.client_payload.url}}" >> "$GITHUB_STEP_SUMMARY"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test
        run: |
          yarn install
          yarn playwright:install
          yarn test --grep "@ID_1"
