name: Run Test and Check PR
run-name: Run GHA by @${{github.actor}}
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL}}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies and browsers
        run: |
          yarn install
          yarn playwright:install
      - name: Check env var is configured
        run: |
          echo "TEST_USER_EMAIL: $TEST_USER_EMAIL"
          echo "TEST_USER_PASSWORD: $TEST_USER_PASSWORD"
      - name: Run tests
        run: |
          yarn test --grep "@ID_1"
